spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://stockexample:3306/stock_example
    username: android
    password: and132!#@
    hikari:
      maximum-pool-size: 40
  redis:
    host: 110.165.16.138

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE